### ISSUE TITLE
Unable to DB_USE_IAM_AUTH with aws RDS instance

### ISSUE THREAD

**Issue by carl-reverb** [pganalyze/collector#378]
Hi, I've attempted to use the new IAM auth with our RDS instance but it did not work. Deployed to kubernetes via custom helm chart.

The instance in question has IAM auth enabled, and I granted the `rds_iam` role to the `pganalyze` user, however the server logs:
```
redacted:pganalyze@redacted:[13984]:LOG:  pam_authenticate failed: Permission denied
redacted:pganalyze@redacted:[13984]:FATAL:  PAM authentication failed for user "pganalyze"
redacted:pganalyze@redacted:[13984]:DETAIL:  Connection matched pg_hba.conf line 13: "hostssl    all             +rds_iam             all            pam"
```
I checked that my superuser could log in (via helper script): 
```
~ $ samiamdb redacted redacted pganalyze redacted
psql (14.7 (Homebrew), server 12.8)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

redacted=> 
```

So I checked IAM for the right policy...
```
{
    "Statement": [
        {
            "Action": [
                "rds:DescribeDBInstances",
                "rds:DescribeDBClusters",
                "cloudwatch:GetMetricStatistics"
            ],
            "Effect": "Allow",
            "Resource": "*",
            "Sid": ""
        },
        {
            "Action": "logs:GetLogEvents",
            "Effect": "Allow",
            "Resource": "arn:aws:logs:*:*:log-group:RDSOSMetrics:log-stream:*",
            "Sid": ""
        },
        {
            "Action": "rds:DescribeDBParameters",
            "Effect": "Allow",
            "Resource": "arn:aws:rds:*:*:pg:*",
            "Sid": ""
        },
        {
            "Action": [
                "rds:DownloadDBLogFilePortion",
                "rds:DescribeDBLogFiles"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:rds:*:*:db:*",
            "Sid": ""
        },
        {
            "Action": "rds-db:connect",
            "Effect": "Allow",
            "Resource": "arn:aws:rds-db:us-east-1:REDACTED:dbuser:REDACTED/pganalyze",
            "Sid": ""
        }
    ],
    "Version": "2012-10-17"
}
```

All seems well here, and pganalyze does seem able to assume this role via the trust relationship and IRSA; verified because when I first deployed there was a bug that resulted in errors from pganalyze about being unable to assume the role. Corrected and resolved.

Next I verify that the correct image is deployed; one which should include the IAM functionality:
```
<snip>
    envFrom:                                                                                                                                                                                 
    - secretRef:                                                                                                                                                                             
        name: core-pganalyze-collector                                                                                                                                                       
        optional: false                                                                                                                                                                      
    image: quay.io/pganalyze/collector:v0.48.0                                                                                                                                               
<snip>
```
Within that secret, `DB_USE_IAM_AUTH` is set to `"true"`. The source code and #368 commentary suggest this should work; and I get no errors about obtaining the token, however the IAM console indicates that "Amazon RDS IAM Authentication" was "Not accessed in the tracking period." whereas other API calls were.

I decided to instead switch back to password auth; revoked the `rds_iam` role from `pganalyze`, and supplied `DB_PASSWORD` in my secret. Thereafter:

```
I [default] Submitted compact activity snapshot successfully                                                                                                                                 
I [default] Submitted compact activity snapshot successfully                                                                                                                                 
I [default] Submitted compact logs snapshot successfully  
```

I'm out of ideas here, would really like to be able to switch over to IAM auth.
