### ISSUE TITLE
Additional security settings for pganalyze collector

### ISSUE THREAD

**Issue by jawnsy** [pganalyze/collector#435]
We've been using these settings successfully for quite some time, so I thought I'd contribute these upstream if it's of interest to you.

Container volumes/security context:

```yaml
          volumeMounts:
            - mountPath: /tmp
              name: scratch
              subPath: tmp
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
```

Pod security context:

```yaml
      securityContext:
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: scratch
          emptyDir: {}
      enableServiceLinks: false
```
